version: '3'
services:
  web:
    image: web-app
    build: ./
    links:
      - postgres
    ports:
      - 3000:3000
    environment:
      - PG_HOST=postgres
    volumes:
      - ./src:/home/node/reward-system-demo/src
      - ./.env:/home/node/reward-system-demo/.env
      - ./public:/home/node/reward-system-demo/public
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=reward-system
    volumes:
      - ~/postgres:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - 127.0.0.1:5432:5432
